name: Call Analysis Workflow

on:
  schedule:
    - cron: '*/30 * * * *'  # Запускать каждые 30 минут
  workflow_dispatch:          # Позволяет запускать вручную

jobs:
  analyze-calls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run analysis script
        env:
          TELFIN_APP_ID: ${{ secrets.TELFIN_APP_ID }}
          TELFIN_APP_SECRET: ${{ secrets.TELFIN_APP_SECRET }}
          YANDEX_SPEECHKIT_KEY: ${{ secrets.YANDEX_SPEECHKIT_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python analyzer.py
